language: python
python: "3.6"

services:
  - docker

before_install:
  - docker pull postgres:10-alpine

before_script:
  - pip install docker-compose
  - docker login --username $DOCKER_USER --password $DOCKER_PASS

script:
  - docker-compose run app sh -c "python manage.py test && flake8"
